
from tests.payments.authorization_capture_test import *
from tests.payments.authorization_get_test import *
from tests.payments.authorization_reauthorize_test import *
from tests.payments.authorization_void_test import *
from tests.payments.capture_get_test import *
from tests.payments.capture_refund_test import *
from tests.payments.order_authorize_test import *
from tests.payments.order_capture_test import *
from tests.payments.order_get_test import *
from tests.payments.order_void_test import *
from tests.payments.payment_create_test import *
from tests.payments.payment_execute_test import *
from tests.payments.payment_get_test import *
from tests.payments.payment_list_test import *
from tests.payments.payment_update_test import *
from tests.payments.refund_get_test import *
from tests.payments.sale_get_test import *
from tests.payments.sale_refund_test import *