
from tests.v1.payments.authorization_capture_test import *
from tests.v1.payments.authorization_get_test import *
from tests.v1.payments.authorization_reauthorize_test import *
from tests.v1.payments.authorization_void_test import *
from tests.v1.payments.capture_get_test import *
from tests.v1.payments.capture_refund_test import *
from tests.v1.payments.order_authorize_test import *
from tests.v1.payments.order_capture_test import *
from tests.v1.payments.order_get_test import *
from tests.v1.payments.order_void_test import *
from tests.v1.payments.payment_create_test import *
from tests.v1.payments.payment_execute_test import *
from tests.v1.payments.payment_get_test import *
from tests.v1.payments.payment_list_test import *
from tests.v1.payments.payment_update_test import *
from tests.v1.payments.refund_get_test import *
from tests.v1.payments.sale_get_test import *
from tests.v1.payments.sale_refund_test import *