from tests.payments.request.authorization_capture_request_test import *
from tests.payments.request.authorization_get_request_test import *
from tests.payments.request.authorization_reauthorize_request_test import *
from tests.payments.request.authorization_void_request_test import *
from tests.payments.request.capture_get_request_test import *
from tests.payments.request.capture_refund_request_test import *
from tests.payments.request.order_authorize_request_test import *
from tests.payments.request.order_capture_request_test import *
from tests.payments.request.order_get_request_test import *
from tests.payments.request.order_void_request_test import *
from tests.payments.request.payment_create_request_test import *
from tests.payments.request.payment_execute_request_test import *
from tests.payments.request.payment_get_request_test import *
from tests.payments.request.payment_list_request_test import *
from tests.payments.request.payment_update_request_test import *
from tests.payments.request.refund_get_request_test import *
from tests.payments.request.sale_get_request_test import *
from tests.payments.request.sale_refund_request_test import *
